### ISSUE TITLE
Some suggestions for the UI

### ISSUE THREAD

**Issue by BlackMesa123** [Lemkinator/NAK-Chor-Gesang-Buch#1]
Wanted to give you some little advices for this app but didn't know how to contact you, so I'm using github issues page in your repo.

- Avoid using icons in TabLayout, doesn't matches OUI Design+ripple background looks odd;
- Avoid showing too much action items in Toolbar, lib still doesn't have showAsAction="ifRoom" support, I suggest you to show just the Search item and hide all the rest (like TabLayout, avoid using icons for items inside the PopupWindow);
- Replace "android:tooltipText" attr in fragment_tab0.xml with the in-library [Tooltip](https://github.com/Yanndroid/OneUI-Design-Library/wiki/Tooltip), global Tooltip window is still not supported in the lib so it still uses Google one;
- Add FastScroller in your ListViews for a better UX. Consider implementing [SectionIndexer](https://developer.android.com/reference/android/widget/SectionIndexer) in your Adapters, it will make the FastScroller behave much better ([example here](https://github.com/Yanndroid/OneUI-Design-Library/blob/6baac3d619488b45fdbd96dd73aa8845480c9ffe/app/src/main/java/de/dlyt/yanndroid/oneuiexample/tabs/IconsTab.java#L555));
- In MainActivityTab1, use TabLayout sesl auto sizing mode. To do this, under your "seslSetSubTabStyle" call, add this:
```java
subTabs.setMode(TabLayout.SESL_MODE_WEIGHT_AUTO);
```
You can use SESL_MODE_FIXED_AUTO if you instead want the tabs to have all the same size.

**Comment by BlackMesa123** [comment]
With these changes, the UI will look more cleaner and also match better OUI design guidelines.

<img src="https://user-images.githubusercontent.com/13062958/157328196-d3d6ecfb-cc6f-48fc-89ae-a7c0cac82f5f.jpeg" height="400"/>

**Comment by Lemkinator** [comment]
> Wanted to give you some little advices for this app but didn't know how to contact you, so I'm using github issues page in your repo.

Wow, didnt see that commin...  🤯 😃  Thanks a lot!! Ive added a public email in my profile now...
>
> * Avoid using icons in TabLayout, doesn't matches OUI Design+ripple background looks odd; 

Jep, changed it
> * Avoid showing too much action items in Toolbar, lib still doesn't have showAsAction="ifRoom" support, I suggest you to show just the Search item and hide all the rest (like TabLayout, avoid using icons for items inside the PopupWindow);

jep, hided the dnd, mute buttons and removed icons, but i kept the changeMode button since its purpose is to quickly change modes without opening the drawer... im gonna think about it, maybe im gonna remove it completely...
> * Replace "android:tooltipText" attr in fragment_tab0.xml with the in-library [Tooltip](https://github.com/Yanndroid/OneUI-Design-Library/wiki/Tooltip), global Tooltip window is still not supported in the lib so it still uses Google one; 

Removed... i used that quite often, cause i didnt really understand it 🤣 😅 
i dont know if im gonna use Tooltips cause most people wont even know how to open/see them... 
talking to "the Master" 😆 : i thought about adding some TipPopups (like on fab in the example) on first app-start instead of tooltips, but i couldnt get that to work... how can i set a TipPopup on an toolbarMenuButton (and also on a custom tabLayout/bnv-Button) on app start (even before i click it)... how can i get the view of those toolbarMenuButtons/tabLayoutButtons?
(with tabLayoutButtons i mean e.g. the plus or minus button in tablayout (earlier bnvMenu) in textview fragment)...

> * Add FastScroller in your ListViews for a better UX. Consider implementing [SectionIndexer](https://developer.android.com/reference/android/widget/SectionIndexer) in your Adapters, it will make the FastScroller behave much better ([example here](https://github.com/Yanndroid/OneUI-Design-Library/blob/6baac3d619488b45fdbd96dd73aa8845480c9ffe/app/src/main/java/de/dlyt/yanndroid/oneuiexample/tabs/IconsTab.java#L555));

hm, the FastScroller was working on my emulator and real devices (S10+) (if i remember it correct, there were some missing class errors (sesl...) but everything worked fine on my side), but on all of my friends devices (e.g. S10e, S21+,...) the app crashed when FastScroller was enabled... i was not able to reproduce that, so i just removed the FastScroller... 
im not familiar with SectionIndexer but the next days im gonna read the docs and try to implement it...

> * In MainActivityTab1, use TabLayout sesl auto sizing mode. To do this, under your "seslSetSubTabStyle" call, add this:
> 
> ```java
> subTabs.setMode(TabLayout.SESL_MODE_WEIGHT_AUTO);
> ```
> 
> You can use SESL_MODE_FIXED_AUTO if you instead want the tabs to have all the same size.

ive added that:
> ```java
> subTabs.setTabMode(TabLayout.SESL_MODE_WEIGHT_AUTO);
> ```




Thanks a lot for spending your time to read my (trash?) code 😅 thats my first app (did some appInventor some years ago, but thats just moving some blocks... 🤣 )
I am very happy for every suggestion/advice 😄

**Comment by BlackMesa123** [comment]
The FastScroller crash isn't your fault, it's a bug that happens when the current Activity is using ThemeUtils. The only way for you to avoid this issue as per today is to use the dev branch build of the lib, do this:

- Extract this archive ([oneui-beta.aar.zip](https://github.com/Lemkinator/NAK-Chor-Gesang-Buch/files/8212161/oneui-beta.aar.zip)) and copy the aar file in the "app/libs" folder of your project
- In the app/build.gradle file, replace the lib implementation with the following:
```gradle
// OneUI Design Library Beta
//implementation 'io.github.yanndroid:oneui:2.3.0'
implementation fileTree(include: ['*.aar'], dir: 'libs')
```

Regarding TipPopup, let's first see how to get the views where the popup will attach:
- For a Toolbar Menu item use:
```java
((ViewGroup) drawerLayout.findViewById(R.id.toolbar_layout_action_menu_item_container)).getChildAt(/* your view index */);
```
- For TabLayout use one of the following:
```java
// Tab View
((ViewGroup) tabLayout.getChildAt(0)).getChildAt(/* your tab index */);
// Tab TextView
tabLayout.getTabAt(/* your tab index */).seslGetTextView();
```

Here's an example of two TipPopup for your MainActivity:
- Declare the TipPopup(s)
```java
private TipPopup tipPopup1;
private TipPopup tipPopup2;
```
- Create the "initTipPopup()" method:
```java
private void init() {
    ...
    setCurrentItem();

    initTipPopup();
}
```

```java
private void initTipPopup() {
    View searchItemView = ((ViewGroup) drawerLayout.findViewById(R.id.toolbar_layout_action_menu_item_container)).getChildAt(0);

    tipPopup1 = new TipPopup(searchItemView);
    tipPopup1.setExpanded(true);
    tipPopup1.setMessage("This is the Search button");
    tipPopup1.setOnDismissListener(() -> tipPopup2.show(TipPopup.DIRECTION_TOP_RIGHT));

    View numberTab = tabLayout.getTabAt(0).seslGetTextView();
    tipPopup2 = new TipPopup(numberTab);
    tipPopup2.setExpanded(true);
    tipPopup2.setMessage("This is the Number tab");
}
```
- Show the Popups:
```java
@Override
public void onAttachedToWindow() {
    super.onAttachedToWindow();
    new Handler().postDelayed(() -> tipPopup1.show(TipPopup.DIRECTION_BOTTOM_LEFT), 300);
}
```

**Comment by BlackMesa123** [comment]
Here's a few small changes to the previously mentioned TipPopup example:
```java
@Override
public void onAttachedToWindow() {
    super.onAttachedToWindow();
    new Handler().postDelayed(() -> {
        View searchItemView = ((ViewGroup) drawerLayout.findViewById(R.id.toolbar_layout_action_menu_item_container)).getChildAt(0);
        int[] outLocation = new int[2];
        searchItemView.getLocationOnScreen(outLocation);

        tipPopup1.setTargetPosition(outLocation[0] + (searchItemView.getWidth() / 2),
                outLocation[1] + (searchItemView.getHeight() / 2) + getResources().getDimensionPixelSize(R.dimen.sesl_action_button_icon_size));
        tipPopup1.show(TipPopup.DIRECTION_BOTTOM_LEFT);
    }, 50);
}

private void initTipPopup() {
    View searchItemView = ((ViewGroup) drawerLayout.findViewById(R.id.toolbar_layout_action_menu_item_container)).getChildAt(0);
    tipPopup1 = new TipPopup(searchItemView);
    tipPopup1.setBackgroundColor(getResources().getColor(R.color.oui_tip_popup_background_color, getTheme()));
    tipPopup1.setExpanded(true);
    tipPopup1.setMessage("Search through all the available items.");
    tipPopup1.setOnDismissListener(() -> tipPopup2.show(TipPopup.DIRECTION_TOP_LEFT));

    View numberTab = tabLayout.getTabAt(2).seslGetTextView();
    tipPopup2 = new TipPopup(numberTab);
    tipPopup2.setBackgroundColor(getResources().getColor(R.color.oui_tip_popup_background_color, getTheme()));
    tipPopup2.setExpanded(true);
    tipPopup2.setMessage("Here you can find all the items you added to favourites.");
}
```

This is the end result:
<img src="https://user-images.githubusercontent.com/13062958/157410141-1741ccaf-0324-4ec5-b10b-e84ef29f44db.png" height="400"/> <img src="https://user-images.githubusercontent.com/13062958/157410150-9304de7f-f0f1-40d2-95f3-c281f54daafb.png" height="400"/>

**Comment by Lemkinator** [comment]
Thanks a lot for the Help!! 
TipPopups, FastScroller and SectionIndexer are now implemented...
Do you have an idea, why the FastScroller was working on all of my devices, but not on my friends'?

2 more issues, but i dont want to ask them in the OUI-Lib-Issues-Tab, cause if it turns out to be my fault, im gonna feel dumb: 😅
- IndexScrollView: when scrolling with indexview and while doing that, switching page on a parent viewpager, the popup of indexScrollView is stuck, until i scroll on the indexscrollview again... is there a way to set an OnChange-listener, so i can disable the parent viewpager when scrolling?
- all those "E/SeslBaseReflector"-errors poppin up in the debug console, e.g. the ": hidden_semIsTextSelectionProgressing NoSuchMethodException" when scrolling on recyclerview , ... is there something i missed or is this normal? can i filter those?

one more thing:
as i'm quite new to all of this stuff, i dont know how all of that works or if this requires much effort and i dont want to ask too much, but it would be nice to have some samsung templates for Wear OS as well.

**Comment by Lemkinator** [comment]
kk, take your time, i'm more than happy with what's there so far!

**Comment by Lemkinator** [comment]
so one more question, cause i cant find any information on the internet:
Im now using the themeColor for the icon in my app and i have seen that in most samsung apps (even google play store with the latest update), they even use the themeColor as primaryColor... how is this done or how can i get the themeColor programmatically?

**Comment by BlackMesa123** [comment]
> so one more question, cause i cant find any information on the internet: Im now using the themeColor for the icon in my app and i have seen that in most samsung apps (even google play store with the latest update), they even use the themeColor as primaryColor... how is this done or how can i get the themeColor programmatically?

To my knowledge, currently there's no way to enable Samsung official app theming in custom apps with the library, this is because the list of the apps that get theming is fixed and without system mods this list can't be modified or modded. By using a package name in the list the app theming works correctly (with the lib internal v3 it works flawlessly, I'm not sure about 2.3.0 and older):

<img src="https://i.imgur.com/oCEDyaQ.jpg" height="300"/>

Seems like Samsung is actually testing out if their proprietary app theming can be independent from frameworks in some apks of their apps, will their engine get updated with A12L?🤔

```xml
<meta-data android:name="theming-meta" android:value="meta_014_clock_package"/>
<meta-data android:name="theming-meta-xml" android:value="@xml/meta_014_clock_package"/>
```

**Comment by Lemkinator** [comment]
Okay 🤷‍♂️ thx
